baseURL = "https://spacekey.info/"
title = "SPACEKEY"
defaultContentLanguage  = "ja"
languageCode = "ja-jp"
googleAnalytics = "UA-38086284-1"
copyright = "© 2012-2020 Dalian Spacekey Information Technology Ltd."
hasCJKLanguage = true
enableRobotsTXT = true
buildFuture = true

[taxonomies]
  tag = "tags"

[Permalinks]
  post = "post/:slug"
